import type { Metadata } from "next";
import { Nunito, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/components/providers/StoryblokProvider";
import { getStoryblokApi } from "@/lib/storyblok";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let headerStory = null;
    let footerStory = null;

    try {
      const storyblokApi = getStoryblokApi();
      const [headerData, footerData] = await Promise.all([
        storyblokApi.get('cdn/stories/global/header', { version: 'draft' }),
        storyblokApi.get('cdn/stories/global/footer', { version: 'draft' }),
      ]);
      headerStory = headerData.data.story;
      footerStory = footerData.data.story;
    } catch (error) {
      console.error('Error fetching global components:', error);
    }

    console.log(headerStory.content);
    console.log(footerStory.content);

  return (
    <html lang="en" className="h-full">
        <body className={`${nunito.variable} ${geistMono.variable} ${lora.variable} antialiased flex flex-col min-h-full`}>
          <StoryblokProvider>
            {headerStory && <Header blok={headerStory.content.body[0]} />}
            <main className="flex-grow">
              {children}
            </main>
            {footerStory && <Footer blok={footerStory.content.body[0]} />}
          </StoryblokProvider>
        </body>
      </html>
  );
}
