import type { Metadata } from "next";
import { Nunito, Lora, Bitcount_Prop_Single } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/components/providers/StoryblokProvider";
import ThemeProvider from "@/components/providers/ThemeProvider";
import MotionProvider from "@/components/providers/MotionProvider";
import { getStoryblokApi } from "@/lib/storyblok";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
  display: "swap",
});

const bitcountPropSingle = Bitcount_Prop_Single({
  variable: "--font-bitcount-prop-single",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "Arial", "sans-serif"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let headerStory = null;
    let footerStory = null;

    try {
      const storyblokApi = getStoryblokApi();
      const [headerData, footerData] = await Promise.all([
        storyblokApi.get('cdn/stories/global/header', { version: 'draft' }),
        storyblokApi.get('cdn/stories/global/footer', { version: 'draft' }),
      ]);
      headerStory = headerData.data.story;
      footerStory = footerData.data.story;
    } catch (error) {
      console.error('Error fetching global components:', error);
    }


  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
        <body className={`${nunito.variable} ${bitcountPropSingle.variable} ${lora.variable} antialiased flex flex-col min-h-full`}>
          <ThemeProvider>
            <StoryblokProvider>
              <MotionProvider>
                {headerStory && <Header blok={headerStory.content.body[0]} />}
                <main className="grow py-10">
                  {children}
                </main>
                {footerStory && <Footer blok={footerStory.content.body[0]} />}
              </MotionProvider>
            </StoryblokProvider>
          </ThemeProvider>
        </body>
      </html>
  );
}
